<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://server.soap.mdp" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://server.soap.mdp" xmlns:intf="http://server.soap.mdp" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->

   <wsdl:portType name="UserManagementService">

   </wsdl:portType>

   <wsdl:binding name="UserManagementServiceSoapBinding" type="impl:UserManagementService">

      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

   </wsdl:binding>

   <wsdl:service name="UserManagementServiceService">

      <wsdl:port binding="impl:UserManagementServiceSoapBinding" name="UserManagementService">

         <wsdlsoap:address location="http://localhost:8080/RESTServer/services/UserManagementService"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
